### ISSUE TITLE
Wagon fails to validate correct wagons

### ISSUE THREAD

**Issue by mcouthon** [cloudify-cosmo/wagon#112]
This is actually probably 2 issues. 

### Issue 1
Steps to reproduce:
* wagon create pip
* wagon validate <RESULTING_WAGON>
The validation will fail.

### Issue 2
The steps to reproduce are the same, but here the cause is clear - after pip install `_`s change to `-`s, and so [this](https://github.com/cloudify-cosmo/wagon/blob/master/wagon.py#L461) fails.
For example, [here's](https://github.com/cloudify-cosmo/cloudify-manager/tree/master/tests/integration_tests/resources/plugins/target_aware_mock) a package on which create/validate will fail.

**Comment by nir0s** [comment]
@mcouthon well, that's actually a pip thing. Even when the package is named `target_mock`, the name when you run `pip freeze` will show `target-mock`.

What we can do, is one of two things:

1. Validate both `_` and `-`.
2. Make sure the package name is always with dashes instead of underscores. I think this is a dangerous option (albeit more aesthetic), so I wouldn't go for it.

**Comment by mcouthon** [comment]
@nir0s Validating both seems sensible (and easy to implement).
