### ISSUE TITLE
supported_platform determination is unstable

### ISSUE THREAD

**Issue by OddBloke** [cloudify-cosmo/wagon#60]
With the advent of manylinux, a wagon can (validly) contain wheels for two platforms. In my case, the two platforms are `linux_x86_64` and `manylinux1_x86_64`.

https://github.com/cloudify-cosmo/wagon/blob/master/wagon/utils.py#L241 assumes that the first non-any platform it finds applies to all wheels in the wagon, which means that a wagon containing exactly the same set of packages (some with `linux_x86_64` and some with `manylinux1_x86_64`) can have a different `supported_platform` depending on the sort order of the directory containing the wheels.

**Comment by nir0s** [comment]
That's true and was a bad assumption to begin with but manylinux1 was not taken under consideration due to the nature of creating such wheels. We're aware of that and will fix it in the new version. 

By the way, you're invited to use the `rearchitecture` branch instead which will completely replace the old wagon and also submit PRs if you wish.

Thanks!

**Comment by nir0s** [comment]
Will be releasing v0.6.0 very soon.

**Comment by tommyjcarpenter** [comment]
I have run into this issue today. What was the reason this issue was closed?
